### ISSUE TITLE
[EDIT] Ajuste de requisito

### ISSUE THREAD

**Issue by lucasaranha** [mm-projetos/Supermercado-App#1]
Como discutido anteriormente em sala, sugerimos que fosse melhor especificado como será feita a recomendação de produtos na aba de "receitas". Quais serão os critérios de indicação do item da receita, por exemplo.

**Comment by brunov1ctor** [comment]
Na aba de receitas o usuário poderá inserir ou buscar novas receitas e personalizar a seu modo, com isso é preciso escolher uma para que o sistema mostre quais são os ingredientes necessários para fazer aquela receita ou algumas variações por exemplo no caso da receita pudim for escolhida o sistema poderá recomendar pudim de chocolate, pudim de leite, pudim de queijo e assim também com as demais.

**Comment by lucasaranha** [comment]
Certo. Mas se houverem restrições de receita? Algum tipo de ingrediente especifico, ou de marca especifica? (uma receita vegetariana, por exemplo).
