### ISSUE TITLE
[ADD] Requisito de login

### ISSUE THREAD

**Issue by lucasaranha** [mm-projetos/Supermercado-App#2]
Discutimos a inclusão dos requisitos de login, que estão ausentes das especificações. Não só, mas também como serão feitos (através de aplicativos de terceiros, cadastro etc).

**Comment by brunov1ctor** [comment]
Para efetuar o cadastro o usuário precisa apenas inserir seu e mail e uma senha, feitos diretamente na tela inicial do aplicativo.

**Comment by gabrielmendes98** [comment]
Lucas, vamos adicionar o requisito de login. Obrigado por lembrar!
