### ISSUE TITLE
Erro no nome do ator dos casos de uso

### ISSUE THREAD

**Issue by gusnunes** [mm-projetos/Supermercado-App#5]
Boa noite
Essa issue é para lembrá-los de modificar o ator no diagrama de "Casos de uso" que tem o nome de "Sistema". Como dito em sala de aula pelo professor Maia, todo o diagrama faz parte do sistema, dessa forma não é correto ter um ator com esse nome

**Comment by yandiaszup** [comment]
Valeu pelo lembrete gustavo, acabamos de resolver este problema no diagrama de casos de uso. Nova versao ja esta disponivel!!!
